import type { Listing } from "@/types/listing";

export const mockListings: Listing[] = [
  {
    id: "listing-001",
    title: "望京 SOHO 附近一居室",
    sourcePlatform: "manual",
    rent: 7200,
    area: 45,
    layout: "1室1厅",
    addressHint: "望京 SOHO 附近",
    district: "朝阳区",
    status: "watching",
    commuteMinutes: 28,
    lifeCircleScore: 8.6,
    compositeScore: 8.2,
    createdAt: "2026-05-01",
  },
  {
    id: "listing-002",
    title: "五道口地铁站附近两居室",
    sourcePlatform: "douban",
    sourceUrl: "https://example.com/listing-002",
    rent: 8600,
    area: 62,
    layout: "2室1厅",
    addressHint: "五道口地铁站附近",
    district: "海淀区",
    status: "shortlisted",
    commuteMinutes: 35,
    lifeCircleScore: 9.1,
    compositeScore: 8.5,
    createdAt: "2026-05-01",
  },
  {
    id: "listing-003",
    title: "东直门商圈附近开间",
    sourcePlatform: "xiaohongshu",
    sourceUrl: "https://example.com/listing-003",
    rent: 6500,
    area: 38,
    layout: "开间",
    addressHint: "东直门商圈附近",
    district: "东城区",
    status: "visited",
    commuteMinutes: 22,
    lifeCircleScore: 8.9,
    compositeScore: 8.0,
    createdAt: "2026-05-01",
  },
];
